### ISSUE TITLE
homework review completed

### ISSUE THREAD

**Issue by hatelove** [DillonLi73/TDD-Day1-Homework#1]
作業完成的不錯，建議如下：
1. excepted拼錯了，是expected
2. return new List<Order> { new Order(1, 1, 11, 21) }
   這個部分，在 C# 中會建議不要寫在 constructor 以參數方式傳進去，而是以 property 的方式來做，例如：
   new List<Product>() {new Product() { Id=1 ,Cost=1 ,Revenue=11,SellPrice=21 }};
   原因是，這樣看得出來11筆資料對應到欄位的模樣，可以讓測試案例更清楚說明，為什麼3筆一組針對cost欄位加總的預期結果為： { 6, 15, 24, 21 }

**Comment by DillonLi73** [comment]
感謝 91 哥 review code
1. 已依據 91 哥的建議修改程式
2. 補上 production code

**Comment by hatelove** [comment]
這邊也提供我的 sample solution 給您參考一下：http://bit.ly/91-tdd-day1-homework-solution

第一版只支援 Product, 第二版則使用 extension method + generic + lambda 來支援任意型別。
